GET http://localhost:8080/api/posts HTTP/1.1
Accept: "application/json"

###

GET http://localhost:8080/api/users HTTP/1.1
Accept: "application/json"

###

POST http://localhost:8080/api/posts HTTP/1.1
content-type: application/json

{
    "title": "SSE API",
    "content": "SSE API is easy to use Promise-based web service client API.",
    "authorId": 1,
    "tags": [
        "fetch",
        "api",
        "http",
        "client"
    ],
    "status": "ACTIVE"
}